<a href="https://colab.research.google.com/github/jsscmaina/machinelearning4102/blob/master/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from numpy import array
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV

In [28]:
from google.colab import files
upload = files.upload()

Saving train_data.csv to train_data (1).csv


In [0]:
data = pd.read_csv('train_data.csv')

In [134]:
#droping missing values
#data.dropna(subset=['Alley','FireplaceQu'],inplace=True)
#data.dropna(axis=1,inplace=True)

#replacing missing values with zero so that numeric data still have float or int datatype
data.fillna(0, inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          1460 non-null   object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [135]:
nominal=['Street','Alley','Utilities','LotConfig','Neighborhood','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Foundation',
         'Heating','Electrical','GarageType','GarageFinish','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition','ExterQual',
         'ExterCond','BsmtCond','KitchenQual','FireplaceQu','GarageQual','GarageCond']
ordinal=['MSZoning','LotShape','LandContour','LandSlope','Condition1','Condition2','BldgType','HouseStyle','BsmtQual','BsmtExposure',
         'BsmtFinType1','BsmtFinType2','HeatingQC','CentralAir','Functional']
target=['SalePrice']
numerical=['LotFrontage','LotArea','OverallQual','OverallCond','YearRemodAdd','YearBuilt','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF',
           'TotalBsmtSF','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr',
           'TotRmsAbvGrd','Fireplaces','GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch',
           'PoolArea','MiscVal','MoSold','YrSold']

categorical_data = data.select_dtypes(include=['object']).copy()
column_names = list(categorical_data.columns)
#categorical_data
column_names
for feature in column_names:
  categorical_data[feature]=categorical_data[feature].astype('category')
for feature in ordinal:
      categorical_data[feature]=categorical_data[feature].cat.codes
categorical_data.head(20)

MSZoning Street Alley  LotShape  ...  Fence MiscFeature SaleType  SaleCondition
0          3   Pave     0         3  ...      0           0       WD         Normal
1          3   Pave     0         3  ...      0           0       WD         Normal
2          3   Pave     0         0  ...      0           0       WD         Normal
3          3   Pave     0         0  ...      0           0       WD        Abnorml
4          3   Pave     0         0  ...      0           0       WD         Normal
5          3   Pave     0         0  ...  MnPrv        Shed       WD         Normal
6          3   Pave     0         3  ...      0           0       WD         Normal
7          3   Pave     0         0  ...      0        Shed       WD         Normal
8          4   Pave     0         3  ...      0           0       WD        Abnorml
9          3   Pave     0         3  ...      0           0       WD         Normal
10         3   Pave     0         3  ...      0           0       WD         Normal
11         3   Pave     0         0  ...      0           0      New        Partial
12         3   Pave     0         1  ...      0           0       WD         Normal
13         3   Pave     0         0  ...      0           0      New        Partial
14         3   Pave     0         0  ...   GdWo           0       WD         Normal
15         4   Pave     0         3  ...  GdPrv           0       WD         Normal
16         3   Pave     0         0  ...      0        Shed       WD         Normal
17         3   Pave     0         3  ...      0        Shed       WD         Normal
18         3   Pave     0         3  ...      0           0       WD         Normal
19         3   Pave     0         3  ...  MnPrv           0      COD        Abnorml

[20 rows x 43 columns]

In [136]:
data_copy = categorical_data.copy()

data_copy = pd.concat([pd.get_dummies(data_copy[nominal]),data_copy],axis=1)
data_copy.drop(nominal,axis=1,inplace=True)
#data_copy
new_data = pd.concat([data_copy,data[numerical],data[target]],axis=1)
new_data

Street_Grvl  Street_Pave  Alley_0  ...  MoSold  YrSold  SalePrice
0               0            1        1  ...       2    2008     208500
1               0            1        1  ...       5    2007     181500
2               0            1        1  ...       9    2008     223500
3               0            1        1  ...       2    2006     140000
4               0            1        1  ...      12    2008     250000
...           ...          ...      ...  ...     ...     ...        ...
1455            0            1        1  ...       8    2007     175000
1456            0            1        1  ...       2    2010     210000
1457            0            1        1  ...       5    2010     266500
1458            0            1        1  ...       4    2010     142125
1459            0            1        1  ...       6    2008     147500

[1460 rows x 235 columns]

In [137]:
all_features = list(new_data.columns)
all_features
X = new_data.loc[:,all_features].values
Y = new_data.loc[:,["SalePrice"]].values
X

array([[0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 2.00000e+00,
        2.00800e+03, 2.08500e+05],
       [0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 5.00000e+00,
        2.00700e+03, 1.81500e+05],
       [0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 9.00000e+00,
        2.00800e+03, 2.23500e+05],
       ...,
       [0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 5.00000e+00,
        2.01000e+03, 2.66500e+05],
       [0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 4.00000e+00,
        2.01000e+03, 1.42125e+05],
       [0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 6.00000e+00,
        2.00800e+03, 1.47500e+05]])

In [138]:
X = StandardScaler().fit_transform(X)
X

array([[-0.06423821,  0.06423821,  0.25782141, ..., -1.5991111 ,
         0.13877749,  0.34727322],
       [-0.06423821,  0.06423821,  0.25782141, ..., -0.48911005,
        -0.61443862,  0.00728832],
       [-0.06423821,  0.06423821,  0.25782141, ...,  0.99089135,
         0.13877749,  0.53615372],
       ...,
       [-0.06423821,  0.06423821,  0.25782141, ..., -0.48911005,
         1.64520971,  1.07761115],
       [-0.06423821,  0.06423821,  0.25782141, ..., -0.8591104 ,
         1.64520971, -0.48852299],
       [-0.06423821,  0.06423821,  0.25782141, ..., -0.1191097 ,
         0.13877749, -0.42084081]])

In [142]:
pca = PCA(n_components=2)
pc_s = pca.fit_transform(X)
pca_data = pd.DataFrame(pc_s,columns=['PC1','PC2'])
#pca_data
final_data = pd.concat([pca_data,data[target]],axis=1)
final_data

PC1       PC2  SalePrice
0     3.453933  0.781387     208500
1    -0.135608 -2.690263     181500
2     4.148528  0.431035     223500
3    -1.428240 -0.129921     140000
4     5.960017  0.453432     250000
...        ...       ...        ...
1455  1.718408  0.423209     175000
1456  0.634842 -3.801212     210000
1457  1.285735  0.395389     266500
1458 -2.951654 -2.449362     142125
1459 -0.794570 -2.229406     147500

[1460 rows x 3 columns]

In [143]:
pca.explained_variance_ratio_

array([0.07274969, 0.03288561])